namespace sergiye.Common;

public enum TASK_LOGON_TYPE
{
	TASK_LOGON_NONE,
	TASK_LOGON_PASSWORD,
	TASK_LOGON_S4U,
	TASK_LOGON_INTERACTIVE_TOKEN,
	TASK_LOGON_GROUP,
	TASK_LOGON_SERVICE_ACCOUNT,
	TASK_LOGON_INTERACTIVE_TOKEN_OR_PASSWORD
}
